watch:
  workers: 10
  schedule: "0 1 * * *"
  jitter: 30s
  firstCheckNotif: false
  runOnStartup: false

defaults:
  watchRepo: true
  notifyOn:
    - new
  maxTags: 1
  sortTags: semver

notif:
  mqtt:
    scheme: mqtt
    host: mqtt-broker
    port: 1883
    usernameFile: /config/notif/mqtt/mqtt_username
    passwordFile: /config/notif/mqtt/mqtt_password
    client: diun
    topic: software/update
    qos: 0
  script:
    cmd: "sh"
    args:
      - -c
      - 'echo "$DIUN_ENTRY_IMAGE" >> /update-queue/update-queue.txt'

providers:
  docker:
    watchByDefault: false
